//! ASS subtitle file writer — 1:1 port of `writers/ass_writer.py`.
//!
//! THIS IS THE SINGLE ROUNDING POINT for timing.
//! Float milliseconds are converted to centiseconds here and only here.

use std::fs;
use std::path::Path;

use crate::subtitles::data::*;

/// Write SubtitleData to ASS file — `write_ass_file`
pub fn write_ass_file(data: &SubtitleData, path: &Path, rounding: &str) -> Result<(), String> {
    let mut lines: Vec<String> = Vec::new();

    let section_order = if data.section_order.is_empty() {
        default_section_order()
    } else {
        data.section_order.clone()
    };

    let mut written_sections: std::collections::HashSet<String> = std::collections::HashSet::new();

    // Write header lines
    for line in &data.header_lines {
        lines.push(line.clone());
    }

    // Write sections in order
    for section in &section_order {
        let section_lower = section.to_lowercase();
        match section_lower.as_str() {
            "[script info]" => {
                write_script_info(data, &mut lines);
                written_sections.insert(section_lower);
            }
            "[v4+ styles]" | "[v4 styles]" => {
                write_styles(data, &mut lines, section);
                written_sections.insert("[v4+ styles]".to_string());
                written_sections.insert("[v4 styles]".to_string());
            }
            "[events]" => {
                write_events(data, &mut lines, rounding);
                written_sections.insert(section_lower);
            }
            "[fonts]" => {
                write_fonts(data, &mut lines);
                written_sections.insert(section_lower);
            }
            "[graphics]" => {
                write_graphics(data, &mut lines);
                written_sections.insert(section_lower);
            }
            "[aegisub project garbage]" => {
                write_aegisub_garbage(data, &mut lines);
                written_sections.insert(section_lower);
            }
            "[aegisub extradata]" => {
                write_aegisub_extradata(data, &mut lines);
                written_sections.insert(section_lower);
            }
            _ => {
                // Custom section
                if let Some((_, section_lines)) = data.custom_sections.iter().find(|(n, _)| n == section) {
                    lines.push(section.clone());
                    lines.extend(section_lines.iter().cloned());
                    lines.push(String::new());
                }
                written_sections.insert(section_lower);
            }
        }
    }

    // Write any sections not in section_order
    if !written_sections.contains("[script info]") && !data.script_info.is_empty() {
        write_script_info(data, &mut lines);
    }
    if !written_sections.contains("[v4+ styles]") && !data.styles.is_empty() {
        write_styles(data, &mut lines, "[V4+ Styles]");
    }
    if !written_sections.contains("[events]") && !data.events.is_empty() {
        write_events(data, &mut lines, rounding);
    }
    if !written_sections.contains("[fonts]") && !data.fonts.is_empty() {
        write_fonts(data, &mut lines);
    }
    if !written_sections.contains("[graphics]") && !data.graphics.is_empty() {
        write_graphics(data, &mut lines);
    }
    if !written_sections.contains("[aegisub project garbage]") && !data.aegisub_garbage.is_empty() {
        write_aegisub_garbage(data, &mut lines);
    }
    if !written_sections.contains("[aegisub extradata]") && !data.aegisub_extradata.is_empty() {
        write_aegisub_extradata(data, &mut lines);
    }

    // Custom sections not in order
    for (section_name, section_lines) in &data.custom_sections {
        if !written_sections.contains(&section_name.to_lowercase()) {
            lines.push(section_name.clone());
            lines.extend(section_lines.iter().cloned());
            lines.push(String::new());
        }
    }

    // Join with \r\n (ASS standard)
    let content = lines.join("\r\n");

    // Handle BOM
    let output = if data.has_bom {
        format!("\u{FEFF}{content}")
    } else {
        content
    };

    fs::write(path, output)
        .map_err(|e| format!("Failed to write ASS file: {e}"))
}

fn default_section_order() -> Vec<String> {
    vec![
        "[Script Info]", "[Aegisub Project Garbage]",
        "[V4+ Styles]", "[Events]", "[Fonts]",
        "[Graphics]", "[Aegisub Extradata]",
    ].into_iter().map(String::from).collect()
}

fn write_script_info(data: &SubtitleData, lines: &mut Vec<String>) {
    lines.push("[Script Info]".to_string());

    if data.script_info.is_empty() {
        lines.push("; Script generated by Video-Sync-GUI".to_string());
        lines.push("ScriptType: v4.00+".to_string());
        lines.push("WrapStyle: 0".to_string());
        lines.push("ScaledBorderAndShadow: yes".to_string());
        lines.push("Collisions: Normal".to_string());
        lines.push(String::new());
        return;
    }

    let has_script_type = data.script_info.iter().any(|(k, _)| k.to_lowercase() == "scripttype");
    let has_collisions = data.script_info.iter().any(|(k, _)| k.to_lowercase() == "collisions");

    for (key, value) in &data.script_info {
        if key == "__comment__" {
            lines.push(value.clone());
        } else {
            lines.push(format!("{key}: {value}"));
        }
    }

    if !has_script_type {
        lines.push("ScriptType: v4.00+".to_string());
    }
    if !has_collisions {
        lines.push("Collisions: Normal".to_string());
    }

    lines.push(String::new());
}

fn write_styles(data: &SubtitleData, lines: &mut Vec<String>, section_name: &str) {
    lines.push(section_name.to_string());
    lines.push(format!("Format: {}", data.styles_format.join(", ")));

    for (_, style) in &data.styles {
        let values = style.to_format_values(&data.styles_format);
        lines.push(format!("Style: {}", values.join(",")));
    }

    lines.push(String::new());
}

fn write_events(data: &SubtitleData, lines: &mut Vec<String>, rounding: &str) {
    lines.push("[Events]".to_string());
    lines.push(format!("Format: {}", data.events_format.join(", ")));

    for event in &data.events {
        let event_type = if event.is_comment { "Comment" } else { "Dialogue" };

        let mut values: Vec<String> = Vec::new();
        for field in &data.events_format {
            let field_lower = field.trim().to_lowercase();
            match field_lower.as_str() {
                "layer" => values.push(event.layer.to_string()),
                "start" => values.push(format_ass_time(event.start_ms, rounding)),
                "end" => values.push(format_ass_time(event.end_ms, rounding)),
                "style" => values.push(event.style.clone()),
                "name" | "actor" => values.push(event.name.clone()),
                "marginl" => values.push(event.margin_l.to_string()),
                "marginr" => values.push(event.margin_r.to_string()),
                "marginv" => values.push(event.margin_v.to_string()),
                "effect" => values.push(event.effect.clone()),
                "text" => values.push(event.text.clone()),
                _ => values.push(String::new()),
            }
        }

        lines.push(format!("{event_type}: {}", values.join(",")));
    }

    lines.push(String::new());
}

fn write_fonts(data: &SubtitleData, lines: &mut Vec<String>) {
    if data.fonts.is_empty() { return; }
    lines.push("[Fonts]".to_string());
    for font in &data.fonts {
        lines.push(format!("fontname: {}", font.name));
        for data_line in font.data.split('\n') {
            lines.push(data_line.to_string());
        }
    }
    lines.push(String::new());
}

fn write_graphics(data: &SubtitleData, lines: &mut Vec<String>) {
    if data.graphics.is_empty() { return; }
    lines.push("[Graphics]".to_string());
    for graphic in &data.graphics {
        lines.push(format!("filename: {}", graphic.name));
        for data_line in graphic.data.split('\n') {
            lines.push(data_line.to_string());
        }
    }
    lines.push(String::new());
}

fn write_aegisub_garbage(data: &SubtitleData, lines: &mut Vec<String>) {
    if data.aegisub_garbage.is_empty() { return; }
    lines.push("[Aegisub Project Garbage]".to_string());
    for (key, value) in &data.aegisub_garbage {
        lines.push(format!("{key}: {value}"));
    }
    lines.push(String::new());
}

fn write_aegisub_extradata(data: &SubtitleData, lines: &mut Vec<String>) {
    if data.aegisub_extradata.is_empty() { return; }
    lines.push("[Aegisub Extradata]".to_string());
    for line in &data.aegisub_extradata {
        lines.push(line.clone());
    }
    lines.push(String::new());
}
